services:
  postgres:
    image: postgres:17
    container_name: quarkus-postgres
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - "5433:5432"
    volumes:
      - /home/root/dockerdata/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:8
    container_name: quarkus-redis
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6378:6379"
    volumes:
      - /home/root/dockerdata/redis:/data
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - /home/root/dockerdata/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/root/dockerdata/nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/root/dockerdata/nginx/html:/usr/share/nginx/html:ro
      - /home/root/dockerdata/nginx/ssl:/etc/nginx/ssl:ro
    restart: always
  hz-serve:
    container_name: quarkus-clever-serve
    image: quarkus/clever_copilot-jvm
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_USERNAME: quarkus_test
      QUARKUS_DATASOURCE_PASSWORD: quarkus_test
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_test
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    volumes:
      -  /home/root/dockerdata/clever:/data
    depends_on:
      - postgres
      - redis