services:
  postgres:
    image: postgres:17
    container_name: quarkus-postgres
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - "5433:5432"
  redis:
    image: redis:8
    container_name: quarkus-redis
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/home/zzx/dockerdata/redis

volumes:
  redis_data:
