services:
  postgres:
    image: postgres:17
    container_name: quarkus-postgres
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: hz_drones
    ports:
      - "5433:5432"
    volumes:
      - /home/root/dockerdata/postgres-drones/data:/var/lib/postgresql/data
  redis:
    image: redis:8
    container_name: quarkus-redis
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6378:6379"
    volumes:
      - /home/root/dockerdata/redis-drones:/data
  nginx:
    image: nginx:latest
    container_name: quarkus-nginx
    ports:
      - "4433:4433"
      - "443:443"
    volumes:
      - /home/root/dockerdata/nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/root/dockerdata/nginx/html:/usr/share/nginx/html:ro
      - /home/root/dockerdata/nginx/ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - hz-serve
  hz-serve:
    container_name: hz-serve-drones
    image: quarkus/hz_server-jvm
    ports:
      - "8080:8080"
    environment:
      QUARKUS_PROFILE: prod 
      QUARKUS_DATASOURCE_USERNAME: quarkus_test
      QUARKUS_DATASOURCE_PASSWORD: quarkus_test
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/hz_drones
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    volumes:
      -  /home/root/dockerdata/drones:/data
    depends_on:
      - postgres
      - redis