version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: quarkus-postgres
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - "5433:5432"
