version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: quarkus_pg
    environment:
      POSTGRES_DB: quarkus_test
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
    ports:
      - "5432:5432"
    volumes:
      - D:/home/zhangzexin/dockerdata/pg:/var/lib/postgresql/data
