services:
  postgres:
    image: postgres:17
    container_name: quarkus-postgres
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - "5433:5432"
    volumes:
      - /home/root/dockerdata/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:8
    container_name: quarkus-redis
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6378:6379"
    volumes:
      - /home/root/dockerdata/redis:/data
  scoring-serve:
    container_name: quarkus-scoring-serve
    image: quarkus/langchain4j-scoring-serve-jvm
    ports:
      - "8081:8081"
    volumes:
      - /data/bge-reranker-base/onnx/model.onnx:/demo/bge-reranker-base/onnx/model.onnx
      - /data/bge-reranker-base/tokenizer.json:/demo/bge-reranker-base/tokenizer.json
  clever-serve:
    container_name: quarkus-clever-serve
    image: quarkus/clever_copilot-jvm
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_USERNAME: quarkus_test
      QUARKUS_DATASOURCE_PASSWORD: quarkus_test
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_test
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    volumes:
      -  /home/root/dockerdata/clever:/data
    depends_on:
      - postgres
      - redis