services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: quarkus_pg_vector
    environment:
      POSTGRES_DB: knowledge
      POSTGRES_USER: huzhi
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - /home/zhangzexin/dockerdata/pgvector:/var/lib/postgresql/data
